FUNCTION_CALLING_DATASET:
  FUNCTION_SAVE_DEST: "pandas_agent/data/pandas_function_openai.json"

VECTORDB:
  BASE_DATABASE_PATH: "pandas_agent/data/PandasDB"
  COLLECTION_NAME: "pandas_docs"
  EMBEDDING_MODEL_NAME: "text-embedding-3-small"
  BATCH_SIZE: 200

PARENTS_SUMMARY:
  SUMMARY_JSON_FILE_PATH: "pandas_agent/data/parent_summary_dict.json"
  OPENAI_LLM_MODEL: "gpt-3.5-turbo-0125"

LEVEL_NODE_LLM:
  OPENAI_LLM_MODEL: "gpt-3.5-turbo-0125"
