FUNCTION_CALLING_DATASET:
  FUNCTION_SAVE_DEST: "data/pandas_function_openai.json"

VECTORDB:
  BASE_DATABASE_PATH: "data/Pandas"
  COLLECTION_NAME: "pandas_docs"
  EMBEDDING_MODEL_NAME: "text-embedding-3-small"

PARENTS_SUMMARY:
  SUMMARY_JSON_FILE_PATH: "data/parent_summary_dict.json"
  LLM_MODEL: "gpt-3.5-turbo"

